<?php

declare(strict_types=1);

// AUTO-GENERATED by .castor/bin/generate-mate-castor-tasks.php — do not edit by hand.
// Regenerate: php .castor/bin/generate-mate-castor-tasks.php  or  castor dev:mate-generate-castor

namespace mate;

use Castor\Attribute\AsArgument;
use Castor\Attribute\AsOption;
use Castor\Attribute\AsTask;
use function CastorTasks\mate_tool_exec;

#[AsTask(name: 'database-query', namespace: 'mate-database', description: 'Runs read-only SQL queries against a Doctrine DBAL connection. Only SELECT and WITH (CTE) queries are allowed. Writes, DDL, and transaction control are blocked. One statement per call — semicolons are rejected; split into separate calls. ROW LIMIT: SELECT without WHERE must include LIMIT 10. Always default to LIMIT 10. Large text columns (>200 chars) are truncated to "<TEXT>" in multi-row results. To see full text, query must return exactly 1 row. Aggregates without GROUP BY (e.g. SELECT COUNT(*)) are exempt from the LIMIT requirement. Before writing SQL, use database-schema to discover table/column names and avoid errors. Connection names come from the application\'s Doctrine DBAL configuration. If `connection` is omitted, the default Doctrine DBAL connection is used.')]
function tool_database_query(
    #[AsArgument(name: 'query', description: 'SQL query to validate and execute in read-only mode')] string $query,
    #[AsOption(name: 'connection', description: 'Optional Doctrine DBAL connection name')] ?string $connection = null
): void {
    $payload = [
        'query' => $query,
        'connection' => $connection,
    ];
    mate_tool_exec('database-query', $payload);
}

#[AsTask(name: 'database-schema', namespace: 'mate-database', description: 'Inspect schema for a Doctrine DBAL connection. Prefer this over raw information_schema/system catalog queries for metadata and definitions. Detail levels: - summary (default): matching table/view names only. - columns: tables with column names, types, nullability, defaults. - full: columns plus indexes, foreign keys, constraints, trigger and routine definitions. Include flags: - includeViews=true adds view names (summary/columns) or view SQL definitions (full). - includeRoutines=true adds procedures, functions, sequences, trigger names (summary/columns) or their definitions (full). Use detail="columns" or detail="full" with a narrow filter whenever possible. filter matches object names; omit or use filter="" to include all objects. Connection names come from the application\'s Doctrine DBAL configuration. If `connection` is omitted, the default Doctrine DBAL connection is used.')]
function tool_database_schema(
    #[AsOption(name: 'connection', description: 'Optional Doctrine DBAL connection name')] ?string $connection = null,
    #[AsOption(name: 'filter', description: 'Optional object-name filter')] string $filter = '',
    #[AsOption(name: 'detail', description: 'One of: summary, columns, full')] string $detail = 'summary',
    #[AsOption(name: 'matchMode', description: 'One of: contains, prefix, exact, glob')] string $matchMode = 'contains',
    #[AsOption(name: 'includeViews', description: 'Include views in the response')] bool $includeViews = false,
    #[AsOption(name: 'includeRoutines', description: 'Include procedures/functions/sequences/triggers in the response')] bool $includeRoutines = false
): void {
    $payload = [
        'connection' => $connection,
        'filter' => $filter,
        'detail' => $detail,
        'matchMode' => $matchMode,
        'includeViews' => $includeViews,
        'includeRoutines' => $includeRoutines,
    ];
    mate_tool_exec('database-schema', $payload);
}

#[AsTask(name: 'monolog-context-search', namespace: 'mate-monolog', description: 'Search log entries by structured context data. Finds entries where a specific context key contains the given value.')]
function tool_monolog_context_search(
    #[AsArgument(name: 'key', description: 'The context field name to search for (e.g. user_id, exception, order_id)')] string $key,
    #[AsArgument(name: 'value', description: 'The value to match in the context field')] string $value,
    #[AsOption(name: 'level', description: 'Filter by log level: DEBUG, INFO, NOTICE, WARNING, ERROR, CRITICAL, ALERT, EMERGENCY')] ?string $level = null,
    #[AsOption(name: 'environment', description: 'Filter by Symfony environment (e.g. dev, prod, test)')] ?string $environment = null,
    #[AsOption(name: 'limit', description: 'Maximum number of entries to return')] int $limit = 100
): void {
    $payload = [
        'key' => $key,
        'value' => $value,
        'level' => $level,
        'environment' => $environment,
        'limit' => $limit,
    ];
    mate_tool_exec('monolog-context-search', $payload);
}

#[AsTask(name: 'monolog-list-channels', namespace: 'mate-monolog', description: 'List all unique Monolog channel names found across log files (e.g. app, security, doctrine).')]
function tool_monolog_list_channels(): void
{
    mate_tool_exec('monolog-list-channels');
}

#[AsTask(name: 'monolog-list-files', namespace: 'mate-monolog', description: 'List available log files with metadata (name, path, size, last modified). Use to discover which logs exist before searching.')]
function tool_monolog_list_files(
    #[AsOption(name: 'environment', description: 'Filter log files by Symfony environment (e.g. dev, prod, test)')] ?string $environment = null
): void {
    $payload = [
        'environment' => $environment,
    ];
    mate_tool_exec('monolog-list-files', $payload);
}

#[AsTask(name: 'monolog-search', namespace: 'mate-monolog', description: 'Search log entries by text or regex pattern. Supports filtering by log level, channel, environment, and date range. Use empty string for term to match all entries when using filters only.')]
function tool_monolog_search(
    #[AsArgument(name: 'term', description: 'Text to search for in log messages, or a regex pattern when $regex is true')] string $term,
    #[AsOption(name: 'regex', description: 'When true, treat $term as a regular expression pattern')] bool $regex = false,
    #[AsOption(name: 'level', description: 'Filter by log level: DEBUG, INFO, NOTICE, WARNING, ERROR, CRITICAL, ALERT, EMERGENCY')] ?string $level = null,
    #[AsOption(name: 'channel', description: 'Filter by Monolog channel name (e.g. app, security, doctrine)')] ?string $channel = null,
    #[AsOption(name: 'environment', description: 'Filter by Symfony environment (e.g. dev, prod, test)')] ?string $environment = null,
    #[AsOption(name: 'from', description: 'Start date filter, any PHP-parseable date string (e.g. 2024-01-01, -1 hour, yesterday)')] ?string $from = null,
    #[AsOption(name: 'to', description: 'End date filter, any PHP-parseable date string')] ?string $to = null,
    #[AsOption(name: 'limit', description: 'Maximum number of entries to return')] int $limit = 100
): void {
    $payload = [
        'term' => $term,
        'regex' => $regex,
        'level' => $level,
        'channel' => $channel,
        'environment' => $environment,
        'from' => $from,
        'to' => $to,
        'limit' => $limit,
    ];
    mate_tool_exec('monolog-search', $payload);
}

#[AsTask(name: 'monolog-tail', namespace: 'mate-monolog', description: 'Get the most recent log entries. Reads from the end of log files, optionally filtered by level and environment.')]
function tool_monolog_tail(
    #[AsOption(name: 'lines', description: 'Number of most recent log entries to return')] int $lines = 50,
    #[AsOption(name: 'level', description: 'Filter by log level: DEBUG, INFO, NOTICE, WARNING, ERROR, CRITICAL, ALERT, EMERGENCY')] ?string $level = null,
    #[AsOption(name: 'environment', description: 'Filter by Symfony environment (e.g. dev, prod, test)')] ?string $environment = null
): void {
    $payload = [
        'lines' => $lines,
        'level' => $level,
        'environment' => $environment,
    ];
    mate_tool_exec('monolog-tail', $payload);
}

#[AsTask(name: 'info', namespace: 'mate-server', description: 'Get PHP runtime environment details: version, OS, OS family, and loaded extensions')]
function tool_server_info(): void
{
    mate_tool_exec('server-info');
}

#[AsTask(name: 'symfony-profiler-get', namespace: 'mate-symfony', description: 'Get a specific profiler profile by its token. Returns detailed profile data including available collectors and resource_uri for accessing collector-specific data.')]
function tool_symfony_profiler_get(
    #[AsArgument(name: 'token', description: 'The unique profiler token identifying the profile')] string $token
): void {
    $payload = [
        'token' => $token,
    ];
    mate_tool_exec('symfony-profiler-get', $payload);
}

#[AsTask(name: 'symfony-profiler-list', namespace: 'mate-symfony', description: 'List and filter Symfony profiler profiles by HTTP method, URL, IP, status code, date range, or context. Profiles are sorted by most recent first, so limit=1 returns the latest profile. Returns summary data with resource_uri for fetching full details via the resource template.')]
function tool_symfony_profiler_list(
    #[AsOption(name: 'limit', description: 'Maximum number of profiles to return (use limit=1 to get the latest profile)')] int $limit = 20,
    #[AsOption(name: 'method', description: 'Filter by HTTP method (GET, POST, PUT, DELETE, PATCH)')] ?string $method = null,
    #[AsOption(name: 'url', description: 'Filter by URL path (partial match supported)')] ?string $url = null,
    #[AsOption(name: 'ip', description: 'Filter by client IP address')] ?string $ip = null,
    #[AsOption(name: 'statusCode', description: 'Filter by HTTP response status code (e.g. 200, 404, 500)')] ?int $statusCode = null,
    #[AsOption(name: 'context', description: 'Filter by Symfony kernel context')] ?string $context = null,
    #[AsOption(name: 'from', description: 'Start date filter for profile creation time')] ?string $from = null,
    #[AsOption(name: 'to', description: 'End date filter for profile creation time')] ?string $to = null
): void {
    $payload = [
        'limit' => $limit,
        'method' => $method,
        'url' => $url,
        'ip' => $ip,
        'statusCode' => $statusCode,
        'context' => $context,
        'from' => $from,
        'to' => $to,
    ];
    mate_tool_exec('symfony-profiler-list', $payload);
}

#[AsTask(name: 'symfony-services', namespace: 'mate-symfony', description: 'Search Symfony dependency injection container services. Optionally filter by service ID or class name. Returns a map of service IDs to their class names.')]
function tool_symfony_services(
    #[AsOption(name: 'query', description: 'Filter services by ID or class name (case-insensitive partial match)')] ?string $query = null
): void {
    $payload = [
        'query' => $query,
    ];
    mate_tool_exec('symfony-services', $payload);
}

